# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title rcpp_estimate_model_ml_Hway
#' @description
#' Estimate (MPLE) parameters for network-separable multilayer network models with up to H-way interactions
#' @name rcpp_estimate_model_ml_Hway
#' @param
#' @examples
#' 
#'
#' @export
rcpp_estimate_model_ml_Hway <- function(RNETWORK, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, random_seeds, g) {
    .Call(`_mlyrnetwork_rcpp_estimate_model_ml_Hway`, RNETWORK, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, random_seeds, g)
}

#' @title rcpp_estimate_model_ml_3way
#' @description
#' Estimate (MPLE) parameters for network-separable multilayer network models with 3-way interactions
#' @name rcpp_estimate_model_ml_3way
#' @param
#' @examples
#' 
#'
#' @export
rcpp_estimate_model_ml_3way <- function(RNETWORK, rNR_tol, rNR_max, rMCMLE_max, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rcheck_chull, random_seeds, g) {
    .Call(`_mlyrnetwork_rcpp_estimate_model_ml_3way`, RNETWORK, rNR_tol, rNR_max, rMCMLE_max, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rcheck_chull, random_seeds, g)
}

#' @title rcpp_estimate_model_ml
#' @description
#' Estimate (MPLE) parameters for network-separable multilayer network models with 2-way interactions
#' @name rcpp_estimate_model_ml
#' @param
#' @examples
#' 
#'
#' @export
rcpp_estimate_model_ml <- function(RNETWORK, rIter_max, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rcheck_chull, random_seeds, g) {
    .Call(`_mlyrnetwork_rcpp_estimate_model_ml`, RNETWORK, rIter_max, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rcheck_chull, random_seeds, g)
}

#' @title rcpp_simulate_ml_LSM
#' @description
#' Simulate a network-separable multilayer network model with basis network generated by latent space model 
#' @name rcpp_simulate_ml_LSM
#' @param
#' @examples
#' 
#' 
#' @export
rcpp_simulate_ml_LSM <- function(rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rtheta, rand_seed, g, fe, nmu, nsd) {
    .Call(`_mlyrnetwork_rcpp_simulate_ml_LSM`, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rtheta, rand_seed, g, fe, nmu, nsd)
}

#' @title rcpp_simulate_ml_SBM
#' @description
#' Simulate a network-separable multilayer network model with basis network generated by stochastic block model
#' @name rcpp_simulate_ml_SBM
#' @param
#' @examples
#' 
#' 
#' @export
rcpp_simulate_ml_SBM <- function(rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rtheta, rand_seed, g, block, p1, p2) {
    .Call(`_mlyrnetwork_rcpp_simulate_ml_SBM`, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rtheta, rand_seed, g, block, p1, p2)
}

#' @title rcpp_simulate_ml
#' @description
#' Simulate a network-separable multilayer network model with 2-way interactions
#' @name rcpp_simulate_ml
#' @param
#' @examples
#' 
#' 
#' @export
rcpp_simulate_ml <- function(rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rtheta, rand_seed, g) {
    .Call(`_mlyrnetwork_rcpp_simulate_ml`, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rtheta, rand_seed, g)
}

#' @title rcpp_simulate_ml_suffstats
#' @description
#' Simulate a network-separable multilayer network model with 2-way interactions and print out sufficient statistics
#' @name rcpp_simulate_ml_suffstats
#' @param
#' @examples
#' rcpp_simulate_ml_suffstats(1,100,1,2,c("withinlayer","crosslayer"),3,2,c(0.4,0.7))
#' 
#' @export
rcpp_simulate_ml_suffstats <- function(rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rtheta, rand_seed, g) {
    .Call(`_mlyrnetwork_rcpp_simulate_ml_suffstats`, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rtheta, rand_seed, g)
}

#' @title rcpp_exact_simulate_ml
#' @description
#' Simulate a network-separable multilayer network model by its exact joint density
#' @name rcpp_exact_simulate_ml
#' @param
#' @examples
#' rcpp_exact_simulate_ml(1,1,3,7,rep("ml_order2",7),10,3,c(0,0.693,0.693,0,0.693,0,0),23333)
#'
#' @export
rcpp_exact_simulate_ml <- function(rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rtheta, rand_seed) {
    .Call(`_mlyrnetwork_rcpp_exact_simulate_ml`, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rtheta, rand_seed)
}

rcpparma_hello_world <- function() {
    .Call(`_mlyrnetwork_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_mlyrnetwork_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_mlyrnetwork_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_mlyrnetwork_rcpparma_bothproducts`, x)
}

