# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title rcpp_compute_dyad_suffstats
#' @description
#' Compute dyadic sufficient statistics for multilayer networks with up to H-way interactions
#' @name rcpp_compute_dyad_suffstats
#' @param
#' @examples
#' 
#'
#' @export
rcpp_compute_dyad_suffstats <- function(RNETWORK, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rhighest_order, rand_seed, arguments) {
    .Call(`_mlyrnetwork_rcpp_compute_dyad_suffstats`, RNETWORK, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rhighest_order, rand_seed, arguments)
}

#' @title rcpp_estimate_model_ml_Hway
#' @description
#' Estimate (MPLE) parameters for network-separable multilayer network models with up to H-way interactions
#' @name rcpp_estimate_model_ml_Hway
#' @param
#' @examples
#' 
#'
#' @export
rcpp_estimate_model_ml_Hway <- function(RNETWORK, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rhighest_order, random_seeds, arguments, itermax) {
    .Call(`_mlyrnetwork_rcpp_estimate_model_ml_Hway`, RNETWORK, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rhighest_order, random_seeds, arguments, itermax)
}

#' @title rcpp_simulate_ml_Hway
#' @description
#' Simulate a network-separable multilayer network model with arbitrary H-way interactions
#' @name rcpp_simulate_ml_Hway
#' @param
#' @examples
#' 
#' 
#' @export
rcpp_simulate_ml_Hway <- function(rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rtheta, rhighest_order, rand_seed, arguments) {
    .Call(`_mlyrnetwork_rcpp_simulate_ml_Hway`, rsamp_num, rburnin, rinterval, rmodel_dim, model_terms, rnum_nodes, rnum_layers, rtheta, rhighest_order, rand_seed, arguments)
}

rcpparma_hello_world <- function() {
    .Call(`_mlyrnetwork_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_mlyrnetwork_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_mlyrnetwork_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_mlyrnetwork_rcpparma_bothproducts`, x)
}

